"""Open the interactive drift map widget using the synthetic KS1-3 test data."""

from __future__ import annotations

import argparse
import atexit
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


NUM_CHANNELS = 4
NUM_TEMPLATES = 2
TEMPLATE_SAMPLES = 61
SAMPLE_RATE = 30_000.0


def _repo_python() -> Path:
    repo_root = Path(__file__).resolve().parent
    if sys.platform == "win32":
        return repo_root / ".conda" / "python.exe"
    return repo_root / ".conda" / "bin" / "python"


def _ensure_supported_python() -> None:
    if sys.version_info >= (3, 10):
        return

    repo_python = _repo_python()
    if repo_python.exists() and Path(sys.executable).resolve() != repo_python.resolve():
        completed = subprocess.run(
            [str(repo_python), str(Path(__file__).resolve()), *sys.argv[1:]],
            check=False,
        )
        raise SystemExit(completed.returncode)

    raise SystemExit(
        "driftplots requires Python 3.10+. "
        f"Run this script with {repo_python} or activate the repo environment first."
    )


_ensure_supported_python()

import numpy as np

SPIKE_SAMPLES = np.array([15_000, 21_000], dtype=np.int64)
SPIKE_TEMPLATE_IDS = np.array([0, 1], dtype=np.int64)
SPIKE_SCALING_AMPLITUDES = np.array([1.5, 0.75], dtype=np.float64)
SPIKE_PC1_FEATURES = np.array(
    [
        [0.0, 3.0, 1.0, 0.0],
        [1.0, -2.0, 0.0, 3.0],
    ],
    dtype=np.float64,
)
NUM_SPIKES = SPIKE_SAMPLES.size
CHANNEL_POSITIONS = np.array(
    [[0.0, 100.0], [0.0, 200.0], [0.0, 300.0], [0.0, 400.0]],
    dtype=np.float64,
)
PC_FEATURE_CHANNEL_INDICES = np.tile(
    np.arange(NUM_CHANNELS, dtype=np.int64),
    (NUM_TEMPLATES, 1),
)

from driftplots.driftplotter import DriftPlotter


def _build_whitening_mat_inv() -> np.ndarray:
    return np.array(
        [
            [1.0, 0.1, 0.0, 0.0],
            [0.1, 1.0, 0.1, 0.0],
            [0.0, 0.1, 1.0, 0.1],
            [0.0, 0.0, 0.1, 1.0],
        ],
        dtype=np.float64,
    )


def _build_whitened_template() -> np.ndarray:
    template = np.zeros((NUM_TEMPLATES, TEMPLATE_SAMPLES, NUM_CHANNELS), dtype=np.float64)
    mid = TEMPLATE_SAMPLES // 2
    waveform_0 = np.array([-2.0, -6.0, -3.0, 1.0, 5.0, 11.0, 4.0], dtype=np.float64)
    template[0, mid - 3: mid + 4, 1] = waveform_0
    template[0, mid - 3: mid + 4, 2] = 0.6 * waveform_0

    waveform_1 = np.array([4.0, 9.0, 3.0, -2.0, -7.0, -10.0, -5.0], dtype=np.float64)
    template[1, mid - 3: mid + 4, 0] = waveform_1
    template[1, mid - 3: mid + 4, 3] = 0.4 * waveform_1
    return template


def write_ks13_test_data(output_dir: Path) -> Path:
    channel_positions = CHANNEL_POSITIONS.copy()
    templates = _build_whitened_template()
    whitening_mat_inv = _build_whitening_mat_inv()

    spike_times = SPIKE_SAMPLES[:, np.newaxis]
    spike_templates = SPIKE_TEMPLATE_IDS[:, np.newaxis]
    amplitudes = SPIKE_SCALING_AMPLITUDES[:, np.newaxis]

    pc_features = np.zeros((NUM_SPIKES, 3, NUM_CHANNELS), dtype=np.float64)
    pc_features[:, 0, :] = SPIKE_PC1_FEATURES
    pc_feature_ind = PC_FEATURE_CHANNEL_INDICES.copy()

    (output_dir / "params.py").write_text(
        f"sample_rate = {SAMPLE_RATE}\n"
        "dtype = 'int16'\n"
        f"n_channels_dat = {NUM_CHANNELS}\n",
        encoding="utf-8",
    )

    np.save(output_dir / "spike_times.npy", spike_times)
    np.save(output_dir / "spike_templates.npy", spike_templates)
    np.save(output_dir / "amplitudes.npy", amplitudes)
    np.save(output_dir / "templates.npy", templates)
    np.save(output_dir / "channel_positions.npy", channel_positions)
    np.save(output_dir / "whitening_mat_inv.npy", whitening_mat_inv)
    np.save(output_dir / "pc_features.npy", pc_features)
    np.save(output_dir / "pc_feature_ind.npy", pc_feature_ind)

    (output_dir / "cluster_group.tsv").write_text(
        "cluster_id\tKSLabel\n0\tgood\n",
        encoding="utf-8",
    )
    (output_dir / "kilosort3.log").write_text("", encoding="utf-8")
    return output_dir


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Open the driftplots interactive widget on synthetic KS1-3 test data.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Optional directory to write the temporary KS1-3 fixture into.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Create the widget and exit without starting the Qt event loop.",
    )
    parser.add_argument(
        "--keep-data",
        action="store_true",
        help="Keep the autogenerated temporary directory after the script exits.",
    )
    return parser


def main() -> int:
    args = _build_arg_parser().parse_args()

    output_dir = args.output_dir
    should_cleanup = False

    if output_dir is None:
        output_dir = Path(tempfile.mkdtemp(prefix="ks13_test_data_"))
        should_cleanup = not args.keep_data
    else:
        output_dir.mkdir(parents=True, exist_ok=True)

    output_dir = output_dir.resolve()
    write_ks13_test_data(output_dir)

    if should_cleanup:
        atexit.register(shutil.rmtree, output_dir, ignore_errors=True)

    plotter = DriftPlotter(output_dir)
    widget = plotter.drift_map_plot_interactive(
        decimate=False,
        exclude_noise=False,
        title="Synthetic KS1-3 test data",
        amplitude_cmap_scaling=(0, 30),
    )

    print(f"Wrote KS1-3 test data to: {output_dir}")
    print(f"Loaded {widget.processed_data.spike_times.size} spikes into the interactive widget.")

    if args.no_show:
        widget.close()
        return 0

    widget.plot()
    widget.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())